### ISSUE TITLE
please check against mpl master

### ISSUE THREAD

**Issue by tacaswell** [jheinen/gr#16]
We are in the process of wrapping up matplotlib v1.5.  

One of the major new features is, when in interactive mode, changing the state of `Artist` objects will trigger a re-draw of the figure.  This relies heavily on the backends to have implemented `draw_idle` (which from quickly skimming https://github.com/jheinen/gr/blob/master/lib/gr/python/gr/matplotlib/backend_gr.py it looks like you do not implement and I don't know enough about the details of `gr` to your implementation of `draw` is lazy or not) to correctly defer actually re-drawing until the screen is ready for an update.

I only became aware of `gr` about 15 minutes ago, but it looks very interesting.  If you would like, could you add a blurb to the mpl docs that this exists (maybe in http://matplotlib.org/devdocs/mpl_toolkits/index.html grouped in a new heading with the iTerm backend?) ?

I would definitely be interested in working together on the mpl backend, please be in touch!

**Comment by jheinen** [comment]
Thanks for the hint. I'll check this ASAP.

I think "High-Level Plotting / GR framework" is a good place for a blurb, although the main idea behind Gr's MPL backend was improving performance and interoperability. May be I find a better place. I'll let you know ...

**Comment by jheinen** [comment]
I made some tests and it seems that ``GR`` is compatible with ``mpl  master`` - so there is no need for urgent action. I will have to take a closer look to the new methods (e.g. ``draw_idle``), may be they will allow further performance improvements.

BTW: I had to patch ``matplotlib/__init__.py`` to get Matpltlib running on OS X (probably due to a bug in ``getdefaultlocale()`` - I don't know, but checking the result and using ``"utf-8"`` as the default encoding helped):

    @contextlib.contextmanager
    def _open_file_or_url(fname):
        if is_url(fname):
            f = urlopen(fname)
            yield _url_lines(f)
            f.close()
        else:
            fname = os.path.expanduser(fname)
            encoding = locale.getdefaultlocale()[1]
            if encoding == None:
                encoding = "utf-8"
            with io.open(fname, encoding=encoding) as f:
                yield f

Glad to see that Florian's PR (https://github.com/matplotlib/matplotlib/pull/3710) is already merged.

**Comment by tacaswell** [comment]
Good to hear.

Can you make an isses/pr on the mpl side with that change? We have a number
of devs who work on this osx so i find it very worrying that there is an
import bug.

draw_idle is very old, it's importance had just increased recently.
