### ISSUE TITLE
interactive camera motion

### ISSUE THREAD

**Issue by nilsbecker** [jheinen/gr#52]
is it currently possible to pan the camera with the mouse? there is a headline in the docs but i did not find anything so far?

**Comment by FlorianRhiem** [comment]
No, but you can build your own system depending on your GUI toolkit and a camera model of your choice by using [`gr3_cameralookat`](https://github.com/jheinen/gr/blob/81b0842dba24af9d879a52c55b89a0b627157cd8/lib/gr3/gr3.h#L122), which positions the camera and orients it for a given center point and an up vector.

**Comment by nilsbecker** [comment]
i saw later that mogli contains a version of this - i may try to copy-and-paste the relevant bits for my purpose. iiuc, this functionality is not included in gr because it depends on the GUI toolkit used? i can understand that. nonetheless i think it would be a nice addition to have some panning and mouse interactivity options out of the box

**Comment by FlorianRhiem** [comment]
Correct, interactivity out of the box isn't possible due to the GUI dependence. What we could do would be to provide callback functions for mouse movement and implement camera movement that way, like I did in [another library](https://github.com/FlorianRhiem/VFRendering/blob/master/src/View.cxx#L64), but there I found that requirements for and opinions on the camera model used can vary widely, both due to different use cases and personal preferences.
